<div>
    <h2><?php echo $this->escape($this->post_title);?></h2>
    <div><?php echo $this->escape($this->post_date);?></div>       
    <div><?php echo $this->escape($this->post_author);?></div>
    <div>
        <a href="<?php echo $this->url(array('controller'=>'index', 'action'=>'edit', 'id'=>$this->id));?>">Редагувати</a>
        <a href="<?php echo $this->url(array('controller'=>'index', 'action'=>'delete', 'id'=>$this->id));?>">Удалить</a>
    </div>
    
    <div><?php echo $this->escape($this->post_content);?></div>
	    
</div>